apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: html-kube-tester

commonLabels:
  app.kubernetes.io/instance: html-kube-tester
  app.kubernetes.io/part-of: html-kube-tester

configMapGenerator:
- name: html-kube-tester-config
  files:
  - config/init.sh
  - config/content-git-repo
  - config/replicas

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

replacements:
  - source:
      kind: ConfigMap
      name: html-kube-tester-config
      fieldPath: data.replicas
    targets:
    - select:
        kind: Deployment
        name: html-kube-tester
      fieldPaths:
      - spec.replicas

patches:
- path: ingress-patch-route-name.yaml
  target:
    kind: Ingress
    name: run